// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOv_S7ArCxzIgtjim8rGIgj_izB3vuBs',
    appId: '1:975899183950:web:c82c29283af7e639a5ac1f',
    messagingSenderId: '975899183950',
    projectId: 'flutter-ihya',
    authDomain: 'flutter-ihya.firebaseapp.com',
    storageBucket: 'flutter-ihya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDSLPJWH1IEedKBjcOsZrdGb7BZnAXpI',
    appId: '1:975899183950:android:bde71fc2f227e8f6a5ac1f',
    messagingSenderId: '975899183950',
    projectId: 'flutter-ihya',
    storageBucket: 'flutter-ihya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgYDxW4u-W-0_421Ulj7EY9874SbG4IsU',
    appId: '1:975899183950:ios:fc71a6141123e8d2a5ac1f',
    messagingSenderId: '975899183950',
    projectId: 'flutter-ihya',
    storageBucket: 'flutter-ihya.appspot.com',
    iosClientId: '975899183950-755beekhkcp1j2bn63nhr69jflt8oaeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihyaFlutterNew',
  );
}
